server.port: ${ALGO_SERVER_PORT:80} # 应用服务 WEB 访问端口

spring: # Spring 配置
  thymeleaf: # Thymeleaf 配置
    enabled: true # 启用 Thymeleaf 模板引擎
    check-template: true # 检查模板语法错误
    cache: true # 启用模板缓存
    mode: HTML # 模板渲染模式
    encoding: UTF-8 # 编码
    content-type: text/html # 内容类型
    prefix: classpath:/templates/ # 模板路径前缀
    suffix: .html # 模板文件后缀

  datasource: # 数据源配置
    url: ${ALGO_DB_URL:jdbc:mysql://101.33.254.198:3306/algo_rating?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${ALGO_DB_USERNAME:root}
    password: ${ALGO_DB_PASSWORD:anivia}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20 # 最大连接数
      connection-timeout: 30000 # 连接超时时间
      idle-timeout: 600000 # 空闲连接超时时间
      max-lifetime: 55000 # 连接存活时间

  jackson: # Jackson 配置
    time-zone: GMT+8 # 时区配置
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式配置

  data:
    redis:
      host: ${ALGO_REDIS_HOST:101.33.254.198}
      port: ${ALGO_REDIS_PORT:6379}
      password: ${ALGO_REDIS_PASSWORD:anivia}
      connect-timeout: 10s # 连接超时时间
      lettuce:
        pool: # Lettuce 连接池配置
          min-idle: 0 # 最小空闲连接数
          max-active: 10 # 最大连接数
          max-wait: -1ms # 最大等待时间
          max-idle: 10 # 最大空闲连接数

  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
# 关闭devtools
#qq机器人反向ws接口
shiro:
  ws:
    server:
      url: /ws/shiro
      enable: true

algo:
  gpt:
    api-key: ${ALGO_GPT_API_KEY:sk-8QoE80jvgRF62CnpJgeuWh5bBkgHp5C7jBYVGaaJNBapDh3C}
  bot:
    groups: ${ALGO_BOT_GROUPS:951214593}
    admin: ${ALGO_BOT_ADMINS:2077353357,3186443553,2128484904}
    bot-qq: ${ALGO_BOT_QQ:948094022}