server.port: 4041 # 应用服务 WEB 访问端口

spring: # Spring 配置
  thymeleaf: # Thymeleaf 配置
    enabled: true # 启用 Thymeleaf 模板引擎
    check-template: true # 检查模板语法错误
    cache: true # 启用模板缓存
    mode: HTML # 模板渲染模式
    encoding: UTF-8 # 编码
    content-type: text/html # 内容类型
    prefix: classpath:/templates/ # 模板路径前缀
    suffix: .html # 模板文件后缀

  datasource: # 数据源配置
    url: jdbc:mysql://8.134.145.217:3306/algo_rating?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: suanxie
    driver-class-name: com.mysql.cj.jdbc.Driver



  jackson: # Jackson 配置
    time-zone: GMT+8 # 时区配置
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式配置

  data:
    redis:
      host: 8.134.145.217
      port: 6379
      password: suanxie
      connect-timeout: 10s # 连接超时时间
      lettuce:
        pool: # Lettuce 连接池配置
          min-idle: 0 # 最小空闲连接数
          max-active: 8 # 最大连接数
          max-wait: -1ms # 最大等待时间
          max-idle: 8 # 最大空闲连接数

  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

# 关闭devtools